version: 2.1

jobs:
  create-a-circleci-artifact:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            echo This is my first CircleCI Job.
            echo This is my second job execution >> artifact.txt
            ls -ls  # This is the command to list all the files in the current directory
            pwd # Show the path where the artifact.txt file is being stored 
      - store_artifacts:
          path: /home/circleci/project/artifact.txt
          destination: artifactFile
  download-a-circleci-artifact:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            curl -H "Circle-Token: $api_token" \
            https://circleci.com/api/v1.1/project/github/technotrainer-student/circleci-devops-training/latest/artifacts \
            | grep -o 'https://[^"]*' \
            | wget --verbose --header "Circle-Token: $api_token"  --input-file -
            cat artifactFile          
  test-environment-variables:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            echo Setting Env Vars
            echo This variable was: $ENV_INSIDE_STEP  
            echo This variable was: $ENV_INSIDE_JOB  
            echo The Current branch is: $CIRCLE_BRANCH
            echo The context variable was: $demoKey
            echo This env var named 'project_var' is: $project_var
         environment: 
           ENV_INSIDE_STEP: set from inside the step
    environment:
      ENV_INSIDE_JOB: set from inside the job
        
workflows:
  first-workflow:
    jobs:
      - create-a-circleci-artifact
      #- download-a-circleci-artifact:
      #    requires:
      #      - create-a-circleci-artifact
      - test-environment-variables: 
          context:
            - my-context
      