version: 2.1

jobs:
  first-circle-ci-job:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            echo This is my first CircleCI Job.
            echo This is my second job execution >> artifact.txt
            ls -ls  # This is the command to list all the files in the current directory
            pwd # Show the path where the artifact.txt file is being stored 
      - store_artifacts:
          path: /home/circleci/project/artifact.txt
          destination: artifactFile
            
workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job
