version: 2.1

jobs:
  first-circle-ci-job:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            echo This is my first CircleCI Job.
      - store_artifacts:
          path: /home/circleci/project/artifact.txt
          destination: artifactFile 
            
workflows:
  first-workflow:
    jobs:
      - first-circle-ci-job