version: 2.1

jobs:
  create-and-upload-artifact:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            echo This is my first CircleCI Job.
            echo This is my second job execution >> artifact.txt
            ls -la # list all files
            pwd # show current path
      - store_artifacts:
          path: /home/circleci/project/artifact.txt
          destination: artifactFile
  download-circle-ci-artifact:
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      - run:
         command:  |
            curl -H "Circle-Token: $api_token"  https://circleci.com/api/v1.1/project/github/technotrainer-student/circleci-devops-training/latest/artifacts | grep -o 'https://[^"]*' | wget --verbose --header "Circle-Token: $api_token"  --input-file -
            cat artifactFile
workflows:
  first-workflow:
    jobs:
      - create-and-upload-artifact
      - download-circle-ci-artifact